module(
    name = "wheelos_map",
    version = "0.1.0",
    compatibility_level = 1,
)

bazel_dep(name = "rules_cc", version = "0.0.9")

bazel_dep(name = "abseil-cpp", version = "20250127.1", repo_name = "com_google_absl")
bazel_dep(name = "eigen", version = "4.0.0-20241125.bcr.2")
bazel_dep(name = "gflags", version = "2.2.2", repo_name = "com_github_gflags_gflags")
bazel_dep(name = "glog", version = "0.7.1", repo_name = "com_github_google_glog")
bazel_dep(name = "googletest", version = "1.17.0", repo_name = "com_google_googletest")
bazel_dep(name = "proj", version = "9.8.0")
bazel_dep(name = "tinyxml2", version = "10.0.0")
bazel_dep(name = "wheelos_common", version = "0.1.1")
bazel_dep(name = "wheelos_core", version = "1.0.4.bcr.1", repo_name = "core")
bazel_dep(name = "wheelos_msgs", version = "0.1.5.bcr.1")
